apiVersion: v1
kind: Service
metadata:
  name: static-web-app-service
  namespace: doit-lab-05
  labels:
    k8s-app: static-web-app
    k8s-scope: gke-ws-doit-lab-05
spec:
  type: LoadBalancer
  selector:
    k8s-app: static-web-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http-80
