apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sidecar-pvc
  namespace: cka-lab-14-extra
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 100Mi