apiVersion: v1
kind: PersistentVolume
metadata:
  name: sidecar-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/logs/shared"