###----------------------------------------
# Static Web App Deployment with 3 Replicas
###----------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-web-app-deployment
  namespace: doit-lab-04
  labels:
    k8s-app: static-web-app
    k8s-scope: gke-ws-doit-lab-04
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: static-web-app
  template:
    metadata:
      labels:
        k8s-app: static-web-app
        k8s-scope: gke-ws-doit-lab-04
    spec:
      containers:
        - name: static-web-app-c
          image: nginx:alpine
          ports:
            - name: http-80
              containerPort: 80
              protocol: TCP