# Taint the node with a key e.g. c1-node2 and set toleration into the deployment so only those pods can be scheduled on that node.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-web-app-deployment-affinity
  namespace: doit-lab-03
  labels:
    k8s-app: static-web-app
    k8s-scope: gke-ws-doit-lab-03
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: static-web-app
  template:
    metadata:
      labels:
        k8s-app: static-web-app
        k8s-scope: gke-ws-doit-lab-03
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html/index.html
            name: index-html
            subPath: index.html
      volumes:
        - name: index-html
          configMap:
            name: static-web-app-index
      tolerations:
      - key: "c1-node2"
        operator: "Equal"
        value: "true"
        effect: "NoExecute"
