apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: cka-lab-14
  labels:
    type: cka-lab-14
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/redis"