apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-claim
  namespace: cka-lab-14
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi